# Generated by Django 3.0.4 on 2020-03-26 13:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDecisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('contribution_credit', models.CharField(choices=[('1', 'Credit me by name on the site'), ('2', 'Do not credit me by name on the site')], max_length=1)),
                ('agreement_and_consent', models.BooleanField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('jurisdiction_within_country', models.TextField(blank=True, null=True)),
                ('court_name', models.CharField(max_length=64)),
                ('decision_location', models.CharField(max_length=64)),
                ('date_of_decision', models.DateField(blank=True)),
                ('link_to_original_decision', models.URLField()),
                ('link_to_english_translation', models.URLField(blank=True)),
                ('background_information', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('result_of_ruling', models.TextField(blank=True, null=True)),
                ('cc_implications', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('contribution_credit', models.CharField(choices=[('1', 'Credit me by name on the site'), ('2', 'Do not credit me by name on the site')], max_length=1)),
                ('agreement_and_consent', models.BooleanField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('title', models.CharField(max_length=64)),
                ('authors', models.CharField(blank=True, max_length=64)),
                ('date_published', models.DateField(blank=True)),
                ('link_to_resource', models.URLField()),
                ('summary', models.TextField()),
                ('is_approved', models.BooleanField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
