# Generated by Django 3.0.5 on 2020-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classimage',
            name='upload_image',
            field=models.ImageField(upload_to='class/'),
        ),
    ]
